services:
    django:
        build: .
        expose:
            - "8000"
        volumes:
            - ./staticfiles:/readme-website/staticfiles
            - ./media:/readme-website/media
            - ./db.sqlite3:/readme-website/db.sqlite3
        restart: unless-stopped

    nginx:
        image: nginx:latest
        ports:
            - "8000:8080"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./staticfiles:/staticfiles:ro
            - ./media:/media:ro
        depends_on:
            - django
